### ISSUE TITLE
Error in compilation with stable version 1.65.0

### ISSUE THREAD

**Issue by lwi19** [alfiedotwtf/travelling_salesman#3]
Hi

I can't compile correctly with the latest stable version of Rust 1.65.:
stable-x86_64-unknown-linux-gnu - Up to date : 1.65.0 (897e37553 2022-11-02)  
OR
nightly-x86_64-unknown-linux-gnu - Up to date : 1.68.0-nightly (dfe3fe710 2022-12-09

I did
git clone https://github.com/alfiedotwtf/travelling_salesman.git
cd travelling_salesman
cargo clean
cargo build
then:...

error: cannot find macro `cfg_if` in this scope
   --> /home/louis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.8/src/error.rs:102:1
    |
102 | cfg_if! {
    | ^^^^^^
    |
    = note: consider importing this macro:
            cfg_if::cfg_if
    = note: `cfg_if` is in scope, but it is a crate, not a macro

error: cannot find macro `cfg_if` in this scope
   --> /home/louis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.8/src/lib.rs:203:1
    |
203 | cfg_if! {
    | ^^^^^^
    |
    = note: consider importing this macro:
            cfg_if::cfg_if
    = note: `cfg_if` is in scope, but it is a crate, not a macro

error[E0425]: cannot find function `os_err` in this scope
   --> /home/louis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.8/src/error.rs:128:32
    |
128 |             if let Some(err) = os_err(errno, &mut buf) {
    |                                ^^^^^^ not found in this scope

error[E0425]: cannot find function `os_err` in this scope
   --> /home/louis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.8/src/error.rs:145:19
    |
145 |             match os_err(errno, &mut buf) {
    |                   ^^^^^^ not found in this scope

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /home/louis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.8/src/lib.rs:290:5
    |
290 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `getrandom` due to 5 previous errors

Thank you

**Comment by lwi19** [comment]
Closed:  Something was wrong in rustup installation (installed since longtime and updated zillion time) 
Everything  compile  correctly after a clean reinstallation of Rust.

**Comment by alfiedotwtf** [comment]
No problem. Feel free to open again if you find it to be a problem.
